micronaut:
  executors:
    io:
      type: fixed
      nThreads: 75
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:token-generator-secret-blah-blah-blah}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:refresh-token-generator-secret}"'
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1...
    walletPassword: micronaut.1
    username: mnocidemo
    password: YOUR_CHOSEN_PASSWORD
jpa:
  default:
    entity-scan:
      packages: "research_exchange.models"
flyway:
  datasources:
    default:
      enabled: true
      cleanOnValidationError: true
      locations: classpath:db/migration
      baseline-version: 0
      baseline-on-migrate: true