CREATE SEQUENCE "USER_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "USER" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "PROFILE_PICTURE_URL" VARCHAR(255),
    "NAME" VARCHAR(255) NOT NULL,
    "USERNAME" VARCHAR(255) UNIQUE NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL, 
    "SALT" BLOB NOT NULL,
    "ROLE" VARCHAR(255) NOT NULL
);

CREATE SEQUENCE "ARTICLE_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "ARTICLE" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(255),
    "SCORE" NUMBER (10),
    "APPROVED" NUMBER(1),
    "DATE_POSTED" DATE NOT NULL,
    "ARTICLE_ABSTRACT" VARCHAR(4000),
    "MAIN_FIELD" VARCHAR(255),
    "SUB_FIELD" VARCHAR(255),
    "PDF_URL" VARCHAR(255),
    "REPO_URL" VARCHAR(255),
    "DATA_URL" VARCHAR(255)
);

CREATE SEQUENCE "TAG_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "TAG" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "NAME" VARCHAR(255),
    "ARTICLE_ID" NUMBER(19)
);

CREATE SEQUENCE "LINK_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "LINK" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "URL" VARCHAR(255),
    "ARTICLE_ID" NUMBER(19)
);

CREATE SEQUENCE "AUTHOR_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "AUTHOR" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL,
    "ARTICLE_ID" NUMBER(19)
);

CREATE SEQUENCE "COMMENT_POST_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "COMMENT_POST" (
    "ID" NUMBER(19) NOT NULL,
    "USER_ID" NUMBER(19) NOT NULL,
    "ARTICLE_ID" NUMBER(19) NOT NULL,
    "SCORE" NUMBER(10) NOT NULL,
    "DATE_POSTED" DATE NOT NULL,
    "CONTENT" VARCHAR(4000) NOT NULL,
    CONSTRAINT pk_comment_post PRIMARY KEY ("ID"),
    CONSTRAINT fk_comment_post_user FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") ON DELETE CASCADE,
    CONSTRAINT fk_comment_post_article FOREIGN KEY ("ARTICLE_ID") REFERENCES "ARTICLE" ("ID") ON DELETE CASCADE
);

CREATE SEQUENCE "GENERAL_COMMENT_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "GENERAL_COMMENT" (
    "ID" NUMBER(19) NOT NULL,
    "COMMENT_POST_ID" NUMBER(19) NOT NULL,
    "THREAD_ID" NUMBER(19),
    "REPLY_TO_ID" NUMBER(19),
    CONSTRAINT pk_general_comment PRIMARY KEY ("ID"),
    CONSTRAINT fk_general_comment_comment_post FOREIGN KEY ("COMMENT_POST_ID") REFERENCES "COMMENT_POST" ("ID") ON DELETE CASCADE,
    CONSTRAINT fk_general_comment_thread FOREIGN KEY ("THREAD_ID") REFERENCES "COMMENT_POST" ("ID") ON DELETE CASCADE,
    CONSTRAINT fk_general_comment_parent FOREIGN KEY ("REPLY_TO_ID") REFERENCES "COMMENT_POST" ("ID") ON DELETE CASCADE
);

CREATE SEQUENCE "EXPERT_REVIEW_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "EXPERT_REVIEW" (
    "ID" NUMBER(19) NOT NULL,
    "COMMENT_POST_ID" NUMBER(19) NOT NULL,
    "STATUS" VARCHAR(255) NOT NULL,
    CONSTRAINT pk_expert_review PRIMARY KEY ("ID"),
    CONSTRAINT fk_expert_review_comment_post FOREIGN KEY ("COMMENT_POST_ID") REFERENCES "COMMENT_POST" ("ID") ON DELETE CASCADE,
    CONSTRAINT check_status_enum CHECK ("STATUS" IN ('Approved', 'Needs Work', 'Rejected'))
);

CREATE SEQUENCE "INLINE_COMMENT_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "INLINE_COMMENT" (
    "ID" NUMBER(19) NOT NULL,
    "COMMENT_POST_ID" NUMBER(19) NOT NULL,
    "EXPERT_REVIEW_ID" NUMBER(19) NOT NULL,
    "PAGE_NUM" NUMBER(10) NOT NULL,
    "SELECTED_CONTENT" VARCHAR(4000) NOT NULL,
    CONSTRAINT pk_inline_comment PRIMARY KEY ("ID"),
    CONSTRAINT fk_inline_comment_comment_post FOREIGN KEY ("COMMENT_POST_ID") REFERENCES "COMMENT_POST" ("ID") ON DELETE CASCADE,
    CONSTRAINT fk_inline_comment_expert_review FOREIGN KEY ("EXPERT_REVIEW_ID") REFERENCES "EXPERT_REVIEW" ("ID") ON DELETE CASCADE
);

CREATE SEQUENCE "HIGHLIGHT_SECTION_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "HIGHLIGHT_SECTION" (
    "ID" NUMBER(19) NOT NULL,
    "INLINE_COMMENT_ID" NUMBER(19) NOT NULL,
    "X_POSITION" NUMBER(10) NOT NULL,
    "Y_POSITION" NUMBER(10) NOT NULL,
    "WIDTH" NUMBER(10) NOT NULL,
    "HEIGHT" NUMBER(10) NOT NULL,
    CONSTRAINT pk_highlight_section PRIMARY KEY ("ID"),
    CONSTRAINT fk_highlight_section_inline_comment FOREIGN KEY ("INLINE_COMMENT_ID") REFERENCES "INLINE_COMMENT" ("ID") ON DELETE CASCADE
);

CREATE SEQUENCE "EXPERT_REQUEST_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "EXPERT_REQUEST" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL,
    "FIELD" VARCHAR(255) NOT NULL,
    "REASON" VARCHAR(255) NOT NULL
);

CREATE SEQUENCE "EXPERT_SEQ" MINVALUE 1 START WITH 1 NOCACHE NOCYCLE;
CREATE TABLE "EXPERT" (
    "ID" NUMBER(19) PRIMARY KEY NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL,
    "FIELD" VARCHAR(255) NOT NULL
);